config/routes.rb
Rails.application.routes.draw do
  resources :phrases
  resources :categories
  resources :custom_phrases, only: [:index, :show, :update, :new, :create, :edit, :destroy]
  namespace :api do 
    namespace :v1 do
      resources :custom_phrases, only: [:index]
    end
  end
  root 'custom_phrases#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/custom_phrase.rb
class CustomPhrase < ApplicationRecord
  has_and_belongs_to_many :phrases
  scope :active, -> { where(active: true) }

  def as_json(options={})
    phrases = self.phrases.map(&:description)
    {
      phrases: phrases.join(", ")
    }
  end 
end

app/models/phrase.rb
class Phrase < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :custom_phrases
end

app/controllers/api/v1/custom_phrases_controller.rb
class Api::V1::CustomPhrasesController < ApplicationController
  def index
    custom_phrases = CustomPhrase.active.all
    render json: custom_phrases
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/custom_phrases_controller.rb
class CustomPhrasesController < ApplicationController
  def index
    @custom_phrases = CustomPhrase.all 
  end
  
  def show
    @custom_phrase = CustomPhrase.find(params[:id])
  end
  
  def new
    @custom_phrase = CustomPhrase.new 
  end
  
  def create
    @custom_phrase = CustomPhrase.new(custom_phrase_params)
    @custom_phrase.save
    redirect_to @custom_phrase
  end
  
  def edit
    @custom_phrase = CustomPhrase.find(params[:id])
  end
  
  def update
    @custom_phrase = CustomPhrase.find(params[:id])
    @custom_phrase.active = params[:custom_phrase][:active]
    @custom_phrase.phrase_ids = params[:custom_phrase][:phrase_ids] 
    @custom_phrase.save
    redirect_to @custom_phrase 
  end 

  def destroy
    @custom_phrase = CustomPhrase.find(params[:id])
    @custom_phrase.destroy
    redirect_to custom_phrases_path  
  end
  
  private 
  
  def custom_phrase_params
    params.require(:custom_phrase).permit(:name, :active, :phrase_ids => []) 
  end 
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  before_action :set_phrase, only: %i[ show edit update destroy ]

  # GET /phrases or /phrases.json
  def index
    @phrases = Phrase.all
  end

  # GET /phrases/1 or /phrases/1.json
  def show
  end

  # GET /phrases/new
  def new
    @phrase = Phrase.new
  end

  # GET /phrases/1/edit
  def edit
  end

  # POST /phrases or /phrases.json
  def create
    @phrase = Phrase.new(phrase_params)

    respond_to do |format|
      if @phrase.save
        format.html { redirect_to phrase_url(@phrase), notice: "Phrase was successfully created." }
        format.json { render :show, status: :created, location: @phrase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phrases/1 or /phrases/1.json
  def update
    respond_to do |format|
      if @phrase.update(phrase_params)
        format.html { redirect_to phrase_url(@phrase), notice: "Phrase was successfully updated." }
        format.json { render :show, status: :ok, location: @phrase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phrases/1 or /phrases/1.json
  def destroy
    @phrase.destroy

    respond_to do |format|
      format.html { redirect_to phrases_url, notice: "Phrase was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phrase
      @phrase = Phrase.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phrase_params
      params.require(:phrase).permit(:description, :category_id)
    end
end

app/helpers/api/v1/custom_phrases_helper.rb
module Api::V1::CustomPhrasesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/custom_phrases_helper.rb
module CustomPhrasesHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/custom_phrases/edit.html.erb
<%= form_for(@custom_phrase) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.select :phrase_ids, options_for_select(Phrase.all.map {|p| [p.description, p.id]}, @custom_phrase.phrase_ids), {}, multiple: true %>
  
  <%= f.submit "Update Custom Phrase" %>
<% end %> 

app/views/custom_phrases/index.html.erb
<h1>Custom Phrase Sets</h1>

<ul>
  <% @custom_phrases.each do |custom_phrase| %>
    <li>
      <%= link_to custom_phrase.name, custom_phrase_path(custom_phrase) %> 
      Active? <%= custom_phrase.active%>
      <%= link_to "Delete", custom_phrase, method: :delete, data: { confirm: "Are you sure?" } %>

    </li>
  <% end %>
</ul>

<%= link_to "New Custom Phrase", new_custom_phrase_path %>

app/views/custom_phrases/new.html.erb
<h1>New Custom Phrase</h1>

<%= form_for(@custom_phrase) do |f| %>
  <%= f.label :name %> 
  <%= f.text_field :name %>
  <%= f.check_box :active %> Active?
  
<table>
  <thead>
    <tr>
      <th>Select</th>
      <th>Description</th>
      <th>Category</th>
    </tr>
  </thead>
  
  <tbody>
    <% Phrase.all.each do |phrase| %>
      <tr>
        <td><%= f.check_box :phrase_ids, { multiple: true }, phrase.id, nil %></td>
        <td><%= phrase.description %></td>
        <td><%= phrase.category.name %></td>
      </tr>
    <% end %> 
  </tbody>
</table> 
  
  <%= f.submit "Create Custom Phrase" %>
<% end %>

app/views/custom_phrases/show.html.erb
<h1><%= @custom_phrase.name %> - <%= @custom_phrase.phrases.count() %></h1>

<ul>
  <% @custom_phrase.phrases.each do |phrase| %>
    <li><%= phrase.description %></li>
  <% end %>
</ul>

<%= form_for(@custom_phrase) do |f| %>
  <%= f.check_box :active %> Active?
  <table>
  <thead>
    <tr>
      <th>Select</th>
      <th>Description</th>
      <th>Category</th>
    </tr>
  </thead>
  
  <tbody>
    <% Phrase.all.each do |phrase| %>
      <tr>
        <td><%= f.check_box :phrase_ids, { multiple: true }, phrase.id, nil %></td>
        <td><%= phrase.description %></td>
        <td><%= phrase.category.name %></td>
      </tr>
    <% end %> 
  </tbody>
</table> 
  <%= f.submit "Update Phrases" %>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EftBack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">EFT BACK</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Phrases", phrases_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Categories", categories_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Custom Phrases", custom_phrases_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav> 
    <%= yield %>
  </body>
</html>

app/views/phrases/_form.html.erb
<%= form_with(model: phrase) do |form| %>
  <% if phrase.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(phrase.errors.count, "error") %> prohibited this phrase from being saved:</h2>

      <ul>
        <% phrase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.number_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/phrases/_phrase.html.erb
<div id="<%= dom_id phrase %>">
  <p>
    <strong>Description:</strong>
    <%= phrase.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= phrase.category_id %>
  </p>

</div>

app/views/phrases/edit.html.erb
<h1>Editing phrase</h1>

<%= render "form", phrase: @phrase %>

<br>

<div>
  <%= link_to "Show this phrase", @phrase %> |
  <%= link_to "Back to phrases", phrases_path %>
</div>

app/views/phrases/index.html.erb
<p style="color: green"><%= notice %></p> 
<h1>Phrases</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phrases.each do |phrase| %>
      <tr>
        <td><%= phrase.description %></td>
        <td><%= phrase.category.name %></td>
        <td><%= link_to "Show", phrase %></td>
        <td><%= link_to "Edit", edit_phrase_path(phrase) %></td> 
        <td><%= link_to "Destroy", phrase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Phrase", new_phrase_path %>

app/views/phrases/new.html.erb
<h1>New phrase</h1>

<%= render "form", phrase: @phrase %>

<br>

<div>
  <%= link_to "Back to phrases", phrases_path %>
</div>

app/views/phrases/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @phrase %>

<div>
  <%= link_to "Edit this phrase", edit_phrase_path(@phrase) %> |
  <%= link_to "Back to phrases", phrases_path %>

  <%= button_to "Destroy this phrase", @phrase, method: :delete %>
</div>